export const list = [
  {
    id: "C-001",
    title: "Combo 1",
    price: "50",
    img: "combo1.jpg",
    category: "combos",
    description: " 1 pollo + papas + ensalada",
  },
  {
    id: "C-002",
    title: "Combo 2",
    price: "60",
    img: "combo2.jpg",
    category: "combos",
    description: " 1 1/4 pollo + papas + ensalada + tequenos + bebida",
  },
  {
    id: "C-003",
    title: "Combo 4",
    price: "70",
    img: "combo3.jpg",
    category: "combos",
    description: " 1 pollo + papas + ensalada + arroz chaufa + bebida",
  },
  {
    id: "B-001",
    title: "Inka Kola",
    price: "15",
    img: "inka.png",
    category: "bebidas",
    description: " Inka Cola 1 1/2 litro",
  },
  {
    id: "B-002",
    title: "Coca Cola",
    price: "12",
    img: "coca.png",
    category: "bebidas",
    description: " Coca Cola 1 1/2 litro",
  },
  {
    id: "B-003",
    title: "Chicha Morada",
    price: "25",
    img: "chica morada.jpg",
    category: "bebidas",
    description: " Chicha Morada Casera 1 1/2 litro (envase de vidrio)",
  },
  {
    id: "CP-001",
    title: "PAPAS AMARILLAS",
    price: "15",
    img: "papas amarillas.jpg",
    category: "complementos",
    description: " Papas amarillas artesanales familiares",
  },
  {
    id: "CP-002",
    title: "CAMOTE",
    price: "16",
    img: "Camote.jpg",
    category: "complementos",
    description: " Camotes artesanales familiares",
  },
  {
    id: "CP-003",
    title: "TEQUENOS",
    price: "20",
    img: "tequenos.jpg",
    category: "complementos",
    description: "Tequenos de queso + Guacamole (12 unidades)", 
  },
];
  
    